CREATE SCHEMA dbo;

CREATE TABLE dbo.VENDEDOR ( 
	ID_VENDEDOR          bigint NOT NULL   IDENTITY,
	NOME                 varchar(100) NOT NULL   ,
	CPF                  varchar(11) NOT NULL   ,
	CONSTRAINT Pk_VENDEDOR_ID_VENDEDOR PRIMARY KEY  ( ID_VENDEDOR ),
	CONSTRAINT unique_cpf UNIQUE ( CPF ) 
 );

CREATE TABLE dbo.CLIENTE ( 
	ID_CLIENTE           bigint NOT NULL   IDENTITY,
	NOME                 varchar(100) NOT NULL   ,
	CNPJ                 varchar(14) NOT NULL   ,
	DATA_NASCIMENTO      datetime    ,
	ID_VENDEDOR          bigint NOT NULL   ,
	CONSTRAINT Pk_CLIENTE_ID_CLIENTE PRIMARY KEY  ( ID_CLIENTE ),
	CONSTRAINT unique_cnpj UNIQUE ( CNPJ ) 
 );

CREATE  INDEX Idx_CLIENTE_ID_VENDEDOR ON dbo.CLIENTE ( ID_CLIENTE );

ALTER TABLE dbo.CLIENTE ADD CONSTRAINT fk_cliente_vendedor FOREIGN KEY ( ID_VENDEDOR ) REFERENCES dbo.VENDEDOR( ID_VENDEDOR ) ON DELETE NO ACTION ON UPDATE NO ACTION;

